
package org.siva.ravipati;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MACHandler", targetNamespace = "http://ravipati.siva.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MACHandler {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://ravipati.siva.org/", className = "org.siva.ravipati.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://ravipati.siva.org/", className = "org.siva.ravipati.GetServerNameResponse")
    public String getServerName();

}
