
package org.siva.ravipati;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MACHandlerService", targetNamespace = "http://ravipati.siva.org/", wsdlLocation = "http://itpcitd42:9090/javabrainsWebServices/MACHandlerService?wsdl")
@HandlerChain(file = "mac_handler.xml")
public class MACHandlerService
    extends Service
{

    private final static URL MACHANDLERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.siva.ravipati.MACHandlerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.siva.ravipati.MACHandlerService.class.getResource(".");
            url = new URL(baseUrl, "http://itpcitd42:9090/javabrainsWebServices/MACHandlerService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://itpcitd42:9090/javabrainsWebServices/MACHandlerService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MACHANDLERSERVICE_WSDL_LOCATION = url;
    }

    public MACHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MACHandlerService() {
        super(MACHANDLERSERVICE_WSDL_LOCATION, new QName("http://ravipati.siva.org/", "MACHandlerService"));
    }

    /**
     * 
     * @return
     *     returns MACHandler
     */
    @WebEndpoint(name = "MAC_Handler")
    public MACHandler getMACHandler() {
        return super.getPort(new QName("http://ravipati.siva.org/", "MAC_Handler"), MACHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MACHandler
     */
    @WebEndpoint(name = "MAC_Handler")
    public MACHandler getMACHandler(WebServiceFeature... features) {
        return super.getPort(new QName("http://ravipati.siva.org/", "MAC_Handler"), MACHandler.class, features);
    }

}
