
package org.siva.ravipati;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestMartCatalog", targetNamespace = "http://ravipati.siva.org/", wsdlLocation = "http://itpcitd40:8080/servOne/TestMartCatalog?wsdl")
public class TestMartCatalog_Service
    extends Service
{

    private final static URL TESTMARTCATALOG_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.siva.ravipati.TestMartCatalog_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.siva.ravipati.TestMartCatalog_Service.class.getResource(".");
            url = new URL(baseUrl, "http://itpcitd40:8080/servOne/TestMartCatalog?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://itpcitd40:8080/servOne/TestMartCatalog?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTMARTCATALOG_WSDL_LOCATION = url;
    }

    public TestMartCatalog_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestMartCatalog_Service() {
        super(TESTMARTCATALOG_WSDL_LOCATION, new QName("http://ravipati.siva.org/", "TestMartCatalog"));
    }

    /**
     * 
     * @return
     *     returns TestMartCatalog
     */
    @WebEndpoint(name = "TestMartCatalogPort")
    public TestMartCatalog getTestMartCatalogPort() {
        return super.getPort(new QName("http://ravipati.siva.org/", "TestMartCatalogPort"), TestMartCatalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestMartCatalog
     */
    @WebEndpoint(name = "TestMartCatalogPort")
    public TestMartCatalog getTestMartCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ravipati.siva.org/", "TestMartCatalogPort"), TestMartCatalog.class, features);
    }

}
